[project]
name = "finalis-hackvidia"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "groq>=0.23.1",
    "matplotlib>=3.10.1",
    "seaborn>=0.13.2",
]
